# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radio.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='radio.proto',
  package='spotify.radio.proto',
  serialized_pb='\n\x0bradio.proto\x12\x13spotify.radio.proto\"a\n\x0cRadioRequest\x12\x0c\n\x04uris\x18\x01 \x03(\t\x12\x0c\n\x04salt\x18\x02 \x01(\x05\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x11\n\tstationId\x18\x05 \x01(\t\x12\x12\n\nlastTracks\x18\x06 \x03(\t\" \n\x10MultiSeedRequest\x12\x0c\n\x04uris\x18\x01 \x03(\t\"8\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"y\n\x06Tracks\x12\x0c\n\x04gids\x18\x01 \x03(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08identity\x18\x03 \x01(\t\x12\x0e\n\x06tokens\x18\x04 \x03(\t\x12/\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x05 \x03(\x0b\x32\x1d.spotify.radio.proto.Feedback\"\xb8\x01\n\x07Station\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08titleUri\x18\x03 \x01(\t\x12\x10\n\x08subtitle\x18\x04 \x01(\t\x12\x13\n\x0bsubtitleUri\x18\x05 \x01(\t\x12\x10\n\x08imageUri\x18\x06 \x01(\t\x12\x12\n\nlastListen\x18\x07 \x01(\x01\x12\r\n\x05seeds\x18\x08 \x03(\t\x12\x10\n\x08thumbsUp\x18\t \x01(\x05\x12\x12\n\nthumbsDown\x18\n \x01(\x05\"\x13\n\x05Rules\x12\n\n\x02js\x18\x01 \x01(\t\"q\n\x0fStationResponse\x12-\n\x07station\x18\x01 \x01(\x0b\x32\x1c.spotify.radio.proto.Station\x12/\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x03(\x0b\x32\x1d.spotify.radio.proto.Feedback\"0\n\x12StationListRequest\x12\x1a\n\x12\x63\x61nReadNewStations\x18\x01 \x01(\x08\"=\n\x0bStationList\x12.\n\x08stations\x18\x01 \x03(\x0b\x32\x1c.spotify.radio.proto.Station\"\x1c\n\rLikedPlaylist\x12\x0b\n\x03uri\x18\x01 \x01(\t\" \n\x10GenreListRequest\x12\x0c\n\x04lang\x18\x01 \x01(\t\"7\n\tGenreList\x12*\n\x06genres\x18\x01 \x03(\x0b\x32\x1a.spotify.radio.proto.Genre\"D\n\x05Genre\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08imageUri\x18\x03 \x01(\t\x12\x0f\n\x07\x62itMask\x18\x04 \x01(\x05')




_RADIOREQUEST = _descriptor.Descriptor(
  name='RadioRequest',
  full_name='spotify.radio.proto.RadioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uris', full_name='spotify.radio.proto.RadioRequest.uris', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='salt', full_name='spotify.radio.proto.RadioRequest.salt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='spotify.radio.proto.RadioRequest.length', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stationId', full_name='spotify.radio.proto.RadioRequest.stationId', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastTracks', full_name='spotify.radio.proto.RadioRequest.lastTracks', index=4,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=133,
)


_MULTISEEDREQUEST = _descriptor.Descriptor(
  name='MultiSeedRequest',
  full_name='spotify.radio.proto.MultiSeedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uris', full_name='spotify.radio.proto.MultiSeedRequest.uris', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=167,
)


_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='spotify.radio.proto.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='spotify.radio.proto.Feedback.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='spotify.radio.proto.Feedback.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='spotify.radio.proto.Feedback.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=225,
)


_TRACKS = _descriptor.Descriptor(
  name='Tracks',
  full_name='spotify.radio.proto.Tracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gids', full_name='spotify.radio.proto.Tracks.gids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='spotify.radio.proto.Tracks.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='spotify.radio.proto.Tracks.identity', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='spotify.radio.proto.Tracks.tokens', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='spotify.radio.proto.Tracks.feedback', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=348,
)


_STATION = _descriptor.Descriptor(
  name='Station',
  full_name='spotify.radio.proto.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='spotify.radio.proto.Station.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='spotify.radio.proto.Station.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='titleUri', full_name='spotify.radio.proto.Station.titleUri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtitle', full_name='spotify.radio.proto.Station.subtitle', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtitleUri', full_name='spotify.radio.proto.Station.subtitleUri', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageUri', full_name='spotify.radio.proto.Station.imageUri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastListen', full_name='spotify.radio.proto.Station.lastListen', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seeds', full_name='spotify.radio.proto.Station.seeds', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thumbsUp', full_name='spotify.radio.proto.Station.thumbsUp', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thumbsDown', full_name='spotify.radio.proto.Station.thumbsDown', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=351,
  serialized_end=535,
)


_RULES = _descriptor.Descriptor(
  name='Rules',
  full_name='spotify.radio.proto.Rules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='js', full_name='spotify.radio.proto.Rules.js', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=537,
  serialized_end=556,
)


_STATIONRESPONSE = _descriptor.Descriptor(
  name='StationResponse',
  full_name='spotify.radio.proto.StationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='station', full_name='spotify.radio.proto.StationResponse.station', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='spotify.radio.proto.StationResponse.feedback', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=558,
  serialized_end=671,
)


_STATIONLISTREQUEST = _descriptor.Descriptor(
  name='StationListRequest',
  full_name='spotify.radio.proto.StationListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canReadNewStations', full_name='spotify.radio.proto.StationListRequest.canReadNewStations', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=673,
  serialized_end=721,
)


_STATIONLIST = _descriptor.Descriptor(
  name='StationList',
  full_name='spotify.radio.proto.StationList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stations', full_name='spotify.radio.proto.StationList.stations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=723,
  serialized_end=784,
)


_LIKEDPLAYLIST = _descriptor.Descriptor(
  name='LikedPlaylist',
  full_name='spotify.radio.proto.LikedPlaylist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='spotify.radio.proto.LikedPlaylist.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=786,
  serialized_end=814,
)


_GENRELISTREQUEST = _descriptor.Descriptor(
  name='GenreListRequest',
  full_name='spotify.radio.proto.GenreListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='spotify.radio.proto.GenreListRequest.lang', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=816,
  serialized_end=848,
)


_GENRELIST = _descriptor.Descriptor(
  name='GenreList',
  full_name='spotify.radio.proto.GenreList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genres', full_name='spotify.radio.proto.GenreList.genres', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=850,
  serialized_end=905,
)


_GENRE = _descriptor.Descriptor(
  name='Genre',
  full_name='spotify.radio.proto.Genre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='spotify.radio.proto.Genre.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='spotify.radio.proto.Genre.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageUri', full_name='spotify.radio.proto.Genre.imageUri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bitMask', full_name='spotify.radio.proto.Genre.bitMask', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=907,
  serialized_end=975,
)

_TRACKS.fields_by_name['feedback'].message_type = _FEEDBACK
_STATIONRESPONSE.fields_by_name['station'].message_type = _STATION
_STATIONRESPONSE.fields_by_name['feedback'].message_type = _FEEDBACK
_STATIONLIST.fields_by_name['stations'].message_type = _STATION
_GENRELIST.fields_by_name['genres'].message_type = _GENRE
DESCRIPTOR.message_types_by_name['RadioRequest'] = _RADIOREQUEST
DESCRIPTOR.message_types_by_name['MultiSeedRequest'] = _MULTISEEDREQUEST
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.message_types_by_name['Tracks'] = _TRACKS
DESCRIPTOR.message_types_by_name['Station'] = _STATION
DESCRIPTOR.message_types_by_name['Rules'] = _RULES
DESCRIPTOR.message_types_by_name['StationResponse'] = _STATIONRESPONSE
DESCRIPTOR.message_types_by_name['StationListRequest'] = _STATIONLISTREQUEST
DESCRIPTOR.message_types_by_name['StationList'] = _STATIONLIST
DESCRIPTOR.message_types_by_name['LikedPlaylist'] = _LIKEDPLAYLIST
DESCRIPTOR.message_types_by_name['GenreListRequest'] = _GENRELISTREQUEST
DESCRIPTOR.message_types_by_name['GenreList'] = _GENRELIST
DESCRIPTOR.message_types_by_name['Genre'] = _GENRE

class RadioRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RADIOREQUEST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.RadioRequest)

class MultiSeedRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MULTISEEDREQUEST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.MultiSeedRequest)

class Feedback(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FEEDBACK

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.Feedback)

class Tracks(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKS

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.Tracks)

class Station(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATION

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.Station)

class Rules(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RULES

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.Rules)

class StationResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATIONRESPONSE

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.StationResponse)

class StationListRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATIONLISTREQUEST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.StationListRequest)

class StationList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATIONLIST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.StationList)

class LikedPlaylist(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LIKEDPLAYLIST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.LikedPlaylist)

class GenreListRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENRELISTREQUEST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.GenreListRequest)

class GenreList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENRELIST

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.GenreList)

class Genre(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENRE

  # @@protoc_insertion_point(class_scope:spotify.radio.proto.Genre)


# @@protoc_insertion_point(module_scope)
