# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='toplist.proto',
  package='',
  serialized_pb='\n\rtoplist.proto\"\x18\n\x07Toplist\x12\r\n\x05items\x18\x01 \x03(\t')




_TOPLIST = descriptor.Descriptor(
  name='Toplist',
  full_name='Toplist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='Toplist.items', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=41,
)

DESCRIPTOR.message_types_by_name['Toplist'] = _TOPLIST

class Toplist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOPLIST
  
  # @@protoc_insertion_point(class_scope:Toplist)

# @@protoc_insertion_point(module_scope)
