# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='playlist4issues.proto',
  package='spotify.playlist4.proto',
  serialized_pb='\n\x15playlist4issues.proto\x12\x17spotify.playlist4.proto\"\xaa\x03\n\x0b\x43lientIssue\x12\x39\n\x05level\x18\x01 \x01(\x0e\x32*.spotify.playlist4.proto.ClientIssue.Level\x12\x37\n\x04\x63ode\x18\x02 \x01(\x0e\x32).spotify.playlist4.proto.ClientIssue.Code\x12\x13\n\x0brepeatCount\x18\x03 \x01(\x05\"q\n\x05Level\x12\x11\n\rLEVEL_UNKNOWN\x10\x00\x12\x0f\n\x0bLEVEL_DEBUG\x10\x01\x12\x0e\n\nLEVEL_INFO\x10\x02\x12\x10\n\x0cLEVEL_NOTICE\x10\x03\x12\x11\n\rLEVEL_WARNING\x10\x04\x12\x0f\n\x0bLEVEL_ERROR\x10\x05\"\x9e\x01\n\x04\x43ode\x12\x10\n\x0c\x43ODE_UNKNOWN\x10\x00\x12\x1c\n\x18\x43ODE_INDEX_OUT_OF_BOUNDS\x10\x01\x12\x19\n\x15\x43ODE_VERSION_MISMATCH\x10\x02\x12\x16\n\x12\x43ODE_CACHED_CHANGE\x10\x03\x12\x17\n\x13\x43ODE_OFFLINE_CHANGE\x10\x04\x12\x1a\n\x16\x43ODE_CONCURRENT_CHANGE\x10\x05\"\x95\x03\n\x13\x43lientResolveAction\x12?\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x31.spotify.playlist4.proto.ClientResolveAction.Code\x12I\n\tinitiator\x18\x02 \x01(\x0e\x32\x36.spotify.playlist4.proto.ClientResolveAction.Initiator\"\xa1\x01\n\x04\x43ode\x12\x10\n\x0c\x43ODE_UNKNOWN\x10\x00\x12\x12\n\x0e\x43ODE_NO_ACTION\x10\x01\x12\x0e\n\nCODE_RETRY\x10\x02\x12\x0f\n\x0b\x43ODE_RELOAD\x10\x03\x12\x1e\n\x1a\x43ODE_DISCARD_LOCAL_CHANGES\x10\x04\x12\x12\n\x0e\x43ODE_SEND_DUMP\x10\x05\x12\x1e\n\x1a\x43ODE_DISPLAY_ERROR_MESSAGE\x10\x06\"N\n\tInitiator\x12\x15\n\x11INITIATOR_UNKNOWN\x10\x00\x12\x14\n\x10INITIATOR_SERVER\x10\x01\x12\x14\n\x10INITIATOR_CLIENT\x10\x02\x42\x1f\n\x1b\x63om.spotify.playlist4.protoH\x01')



_CLIENTISSUE_LEVEL = descriptor.EnumDescriptor(
  name='Level',
  full_name='spotify.playlist4.proto.ClientIssue.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LEVEL_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEVEL_DEBUG', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEVEL_INFO', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEVEL_NOTICE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEVEL_WARNING', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEVEL_ERROR', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=203,
  serialized_end=316,
)

_CLIENTISSUE_CODE = descriptor.EnumDescriptor(
  name='Code',
  full_name='spotify.playlist4.proto.ClientIssue.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CODE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_INDEX_OUT_OF_BOUNDS', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_VERSION_MISMATCH', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_CACHED_CHANGE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_OFFLINE_CHANGE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_CONCURRENT_CHANGE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=319,
  serialized_end=477,
)

_CLIENTRESOLVEACTION_CODE = descriptor.EnumDescriptor(
  name='Code',
  full_name='spotify.playlist4.proto.ClientResolveAction.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CODE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_NO_ACTION', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_RETRY', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_RELOAD', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_DISCARD_LOCAL_CHANGES', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_SEND_DUMP', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CODE_DISPLAY_ERROR_MESSAGE', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=644,
  serialized_end=805,
)

_CLIENTRESOLVEACTION_INITIATOR = descriptor.EnumDescriptor(
  name='Initiator',
  full_name='spotify.playlist4.proto.ClientResolveAction.Initiator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INITIATOR_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATOR_SERVER', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INITIATOR_CLIENT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=807,
  serialized_end=885,
)


_CLIENTISSUE = descriptor.Descriptor(
  name='ClientIssue',
  full_name='spotify.playlist4.proto.ClientIssue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='level', full_name='spotify.playlist4.proto.ClientIssue.level', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='code', full_name='spotify.playlist4.proto.ClientIssue.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeatCount', full_name='spotify.playlist4.proto.ClientIssue.repeatCount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTISSUE_LEVEL,
    _CLIENTISSUE_CODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=477,
)


_CLIENTRESOLVEACTION = descriptor.Descriptor(
  name='ClientResolveAction',
  full_name='spotify.playlist4.proto.ClientResolveAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='spotify.playlist4.proto.ClientResolveAction.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initiator', full_name='spotify.playlist4.proto.ClientResolveAction.initiator', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTRESOLVEACTION_CODE,
    _CLIENTRESOLVEACTION_INITIATOR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=480,
  serialized_end=885,
)

_CLIENTISSUE.fields_by_name['level'].enum_type = _CLIENTISSUE_LEVEL
_CLIENTISSUE.fields_by_name['code'].enum_type = _CLIENTISSUE_CODE
_CLIENTISSUE_LEVEL.containing_type = _CLIENTISSUE;
_CLIENTISSUE_CODE.containing_type = _CLIENTISSUE;
_CLIENTRESOLVEACTION.fields_by_name['code'].enum_type = _CLIENTRESOLVEACTION_CODE
_CLIENTRESOLVEACTION.fields_by_name['initiator'].enum_type = _CLIENTRESOLVEACTION_INITIATOR
_CLIENTRESOLVEACTION_CODE.containing_type = _CLIENTRESOLVEACTION;
_CLIENTRESOLVEACTION_INITIATOR.containing_type = _CLIENTRESOLVEACTION;
DESCRIPTOR.message_types_by_name['ClientIssue'] = _CLIENTISSUE
DESCRIPTOR.message_types_by_name['ClientResolveAction'] = _CLIENTRESOLVEACTION

class ClientIssue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTISSUE
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.ClientIssue)

class ClientResolveAction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTRESOLVEACTION
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.ClientResolveAction)

# @@protoc_insertion_point(module_scope)
