# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import playlist4meta_pb2
import playlist4issues_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='playlist4content.proto',
  package='spotify.playlist4.proto',
  serialized_pb='\n\x16playlist4content.proto\x12\x17spotify.playlist4.proto\x1a\x13playlist4meta.proto\x1a\x15playlist4issues.proto\"P\n\x04Item\x12\x0b\n\x03uri\x18\x01 \x02(\t\x12;\n\nattributes\x18\x02 \x01(\x0b\x32\'.spotify.playlist4.proto.ItemAttributes\"Y\n\tListItems\x12\x0b\n\x03pos\x18\x01 \x02(\x05\x12\x11\n\ttruncated\x18\x02 \x02(\x08\x12,\n\x05items\x18\x03 \x03(\x0b\x32\x1d.spotify.playlist4.proto.Item\"+\n\x0c\x43ontentRange\x12\x0b\n\x03pos\x18\x01 \x02(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\xb3\x03\n\x14ListContentSelection\x12\x14\n\x0cwantRevision\x18\x01 \x01(\x08\x12\x12\n\nwantLength\x18\x02 \x01(\x08\x12\x16\n\x0ewantAttributes\x18\x03 \x01(\x08\x12\x14\n\x0cwantChecksum\x18\x04 \x01(\x08\x12\x13\n\x0bwantContent\x18\x05 \x01(\x08\x12;\n\x0c\x63ontentRange\x18\x06 \x01(\x0b\x32%.spotify.playlist4.proto.ContentRange\x12\x10\n\x08wantDiff\x18\x07 \x01(\x08\x12\x14\n\x0c\x62\x61seRevision\x18\x08 \x01(\x0c\x12\x14\n\x0chintRevision\x18\t \x01(\x0c\x12\x1d\n\x15wantNothingIfUpToDate\x18\n \x01(\x08\x12\x19\n\x11wantResolveAction\x18\x0c \x01(\x08\x12\x34\n\x06issues\x18\r \x03(\x0b\x32$.spotify.playlist4.proto.ClientIssue\x12\x43\n\rresolveAction\x18\x0e \x03(\x0b\x32,.spotify.playlist4.proto.ClientResolveActionB\x1f\n\x1b\x63om.spotify.playlist4.protoH\x01')




_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='spotify.playlist4.proto.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uri', full_name='spotify.playlist4.proto.Item.uri', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='spotify.playlist4.proto.Item.attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=175,
)


_LISTITEMS = descriptor.Descriptor(
  name='ListItems',
  full_name='spotify.playlist4.proto.ListItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pos', full_name='spotify.playlist4.proto.ListItems.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='truncated', full_name='spotify.playlist4.proto.ListItems.truncated', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='items', full_name='spotify.playlist4.proto.ListItems.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=266,
)


_CONTENTRANGE = descriptor.Descriptor(
  name='ContentRange',
  full_name='spotify.playlist4.proto.ContentRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pos', full_name='spotify.playlist4.proto.ContentRange.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='spotify.playlist4.proto.ContentRange.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=268,
  serialized_end=311,
)


_LISTCONTENTSELECTION = descriptor.Descriptor(
  name='ListContentSelection',
  full_name='spotify.playlist4.proto.ListContentSelection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='wantRevision', full_name='spotify.playlist4.proto.ListContentSelection.wantRevision', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantLength', full_name='spotify.playlist4.proto.ListContentSelection.wantLength', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantAttributes', full_name='spotify.playlist4.proto.ListContentSelection.wantAttributes', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantChecksum', full_name='spotify.playlist4.proto.ListContentSelection.wantChecksum', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantContent', full_name='spotify.playlist4.proto.ListContentSelection.wantContent', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contentRange', full_name='spotify.playlist4.proto.ListContentSelection.contentRange', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantDiff', full_name='spotify.playlist4.proto.ListContentSelection.wantDiff', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='baseRevision', full_name='spotify.playlist4.proto.ListContentSelection.baseRevision', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hintRevision', full_name='spotify.playlist4.proto.ListContentSelection.hintRevision', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantNothingIfUpToDate', full_name='spotify.playlist4.proto.ListContentSelection.wantNothingIfUpToDate', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wantResolveAction', full_name='spotify.playlist4.proto.ListContentSelection.wantResolveAction', index=10,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='issues', full_name='spotify.playlist4.proto.ListContentSelection.issues', index=11,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resolveAction', full_name='spotify.playlist4.proto.ListContentSelection.resolveAction', index=12,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=314,
  serialized_end=749,
)

_ITEM.fields_by_name['attributes'].message_type = playlist4meta_pb2._ITEMATTRIBUTES
_LISTITEMS.fields_by_name['items'].message_type = _ITEM
_LISTCONTENTSELECTION.fields_by_name['contentRange'].message_type = _CONTENTRANGE
_LISTCONTENTSELECTION.fields_by_name['issues'].message_type = playlist4issues_pb2._CLIENTISSUE
_LISTCONTENTSELECTION.fields_by_name['resolveAction'].message_type = playlist4issues_pb2._CLIENTRESOLVEACTION
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['ListItems'] = _LISTITEMS
DESCRIPTOR.message_types_by_name['ContentRange'] = _CONTENTRANGE
DESCRIPTOR.message_types_by_name['ListContentSelection'] = _LISTCONTENTSELECTION

class Item(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEM
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.Item)

class ListItems(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTITEMS
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.ListItems)

class ContentRange(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTENTRANGE
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.ContentRange)

class ListContentSelection(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTCONTENTSELECTION
  
  # @@protoc_insertion_point(class_scope:spotify.playlist4.proto.ListContentSelection)

# @@protoc_insertion_point(module_scope)
